name: u_coffee
description: Приложение для графиков кофейни Ю кофе.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1 # Библиотека для дат и валют

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
