name: yu_coffee_web
description: A new Flutter Web project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
flutter:
  uses-material-design: true
