name: u_coffee
description: Coffee shop management app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.24.0
  cloud_firestore: ^4.15.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
